### ISSUE TITLE
Reservation Validation

### ISSUE THREAD

**Issue by Kyosukke** [thingthing/phybee#1]
I need a service to add an entry in the database to validate the reservation.

Table : reservation
Value : Number of ticket per type, total amount, movie choosen and slot choosen

**Comment by thingthing** [comment]
What are the types of the argument that you will give me?

**Comment by Kyosukke** [comment]
Adult : Integer
Child : Integer
Disabled : Integer
Total : Double
Movie : Integer
Schedule : Integer

**Comment by Kyosukke** [comment]
User : Integer

**Comment by thingthing** [comment]
Done
